name: Netlify preview
on:
  workflow_dispatch:
    inputs:
      egaproNextBranch:
        description: "Branche principale (Next.js, pour consultation et futurs fronts)"
        required: true
        default: "feat/egapro-next-merge"
      simuBranch:
        description: "Branche pour la simulation-déclaration"
        required: true
        default: "feat/egapro-next-merge"
      declaBranch:
        description: "Branche pour la déclaration directe"
        required: true
        default: "master"
      apiUrl:
        description: "URL de l'API"
        required: true
        default: "https://dev.egapro.fabrique.social.gouv.fr/api"
      netlifySiteId:
        description: "Id of the Netlify site"
        required: false

concurrency:
  cancel-in-progress: true
  group: netlify-deploy-${{ github.ref }}

jobs:

  build-consultation:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.inputs.egaproNextBranch}}
        repository: "SocialGouv/egapro-next"

    - name: Install Dependencies
      run: |
        yarn install --frozen-lockfile --force --non-interactive

    - name: Build app
      run: yarn build
      env:
        CI: false
        NEXT_PUBLIC_API_URL: ${{github.event.inputs.apiUrl}}

    - name: Export app
      run: yarn export

    - name: Upload react build
      uses: actions/upload-artifact@v2
      with:
        name: egapro-next-export
        path: out

  build-simulation:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.inputs.simuBranch}}
        repository: "SocialGouv/egapro"

    - name: Install Dependencies
      run: |
        yarn install --frozen-lockfile --force --non-interactive

    - name: Build app
      run: yarn build
      env:
        CI: false
        REACT_APP_EGAPRO_API_URL: ${{github.event.inputs.apiUrl}}

    - name: Upload react build
      uses: actions/upload-artifact@v2
      with:
        name: simulation-export
        path: build

  build-declaration:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.inputs.declaBranch}}
        repository: "SocialGouv/egapro-declaration"

    - name: Update API URL in Jekyll config
      run: |
        echo "EGAPRO_API_URL: ${{github.event.inputs.apiUrl}}" >> _config.yml

    - name: Install Jekyll
      run: |
        gem install -n /usr/local/bin jekyll bundler --user-install

    - name: Build Jekyll app
      run: |
        jekyll build --baseurl "/declaration"

    - name: Upload _site artifact
      uses: actions/upload-artifact@v2
      with:
        name: declaration-export
        path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: [build-consultation, build-simulation, build-declaration]
    steps:

    - uses: actions/download-artifact@v2
      with:
        name: egapro-next-export
        path: dist

    - uses: actions/download-artifact@v2
      with:
        name: simulation-export
        path: dist/simulation

    - uses: actions/download-artifact@v2
      with:
        name: declaration-export
        path: dist/declaration

    - name: debug
      run: |
        ls -lah
        ls -lah dist/
        ls -lah dist/declaration/

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: ./dist
        production-deploy: true
        deploy-message: "Branche simulation: ${{ github.event.inputs.simuBranch }} / Branche déclaration: ${{ github.event.inputs.declaBranch }}"
      env:
        NETLIFY_SITE_ID: ${{ github.event.inputs.netlifySiteId || secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
